---
# vars file for monitoring

prometheus_version : 2.53.3
prometheus_url : "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"


prometheus_server : 192.168.10.10
#alertmanager_url : https://github.com/prometheus/alertmanager/releases/download/v0.28.1/alertmanager-0.28.1.linux-amd64.tar.gz

#node_exporter_url : https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz




#grafana_url: 
